### ISSUE TITLE
第四題

### ISSUE THREAD

**Issue by hao860524** [NCU-CSIE-Algorithmics-A-1061/Homework-3#1]
第二組負責

**Comment by jimmylu1220** [comment]
[HW3_第四題.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-3/files/1372128/HW3_.pptx)

**Comment by scps940707** [comment]
我真的很努力去看你們的投影片了，不過還是看不太懂...

1. ```profit >= profit_max``` 為什麼不要大於再做？
2. 變數命名的部分... ```day_buy``` 和 ```day_sold``` 應該是指買進和賣出日？```day_min```具體是指什麼？還有 ```profit_temp``` 是存了什麼？從這段...虛擬碼(?)看不出來...

題目只要你們設計出一個演算法就可以，所以不用實作出來，感覺你們想要用 pseudo code 表達卻又過於艱澀難懂...

**Comment by kuoys** [comment]
1. 這一個我也不清楚，我是覺得大於再做就好。
2. day_buy 和day_sold 確實是買進和賣出日。day_min 主要是想把目前價格最低點的日期存下來。
 然後profit_temp 是筆誤，應該是profit(目前價格減去最低點)
pseudo code的部分會改進後上傳新的ppt。

**Comment by jimmylu1220** [comment]
[HW3_第四題_v2.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-3/files/1388295/HW3_._v2.pptx)

**Comment by c910335** [comment]
我記得上週有請你們更新對吧？
所以說那個更新呢？

**Comment by hao860524** [comment]
[Uploading HW3_第四題_modified.pptx…]()

**Comment by hao860524** [comment]
[HW3_第四題_modified.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-3/files/1410639/HW3_._modified.pptx)

**Comment by c910335** [comment]
`day_buy` 是三小
這個問題我演習課時有告訴你們了吧

**Comment by c910335** [comment]
`day_min` 一開始設為 1
可是迴圈從 0 開始？？？

**Comment by hao860524** [comment]
已修正
[HW3_第四題_modified.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-3/files/1413403/HW3_._modified.pptx)
