### ISSUE TITLE
第一題

### ISSUE THREAD

**Issue by TommyWu-fdgkhdkgh** [NCU-CSIE-Algorithmics-A-1061/Homework-3#3]

**Comment by TommyWu-fdgkhdkgh** [comment]
第十七組負責～

用master theorem

![22359320_1182439738566493_1552602764_n](https://user-images.githubusercontent.com/16782102/31328243-858d7c38-ad06-11e7-8a12-3cc34be17a77.jpg)

**Comment by scps940707** [comment]
請問您的投影片呢？圖片內容是沒什麼問題（雖然不盡詳細），只缺投影片了

**Comment by TommyWu-fdgkhdkgh** [comment]
[algo.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-3/files/1385914/algo.pptx)

**Comment by scps940707** [comment]
你們的投影片 Master Theorem 的 log 都寫反了，檢查一下吧...

**Comment by chellechia** [comment]
[algo_v2.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-3/files/1389534/algo_v2.pptx)

**Comment by chellechia** [comment]
改成根號n的
[algo_v3.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-3/files/1389579/algo_v3.pptx)
